name: test

on:
  pull_request:
    branches: [ main ]
    types: [opened, ready_for_review]

jobs:
  fix-code-style:
    if: '! github.event.pull_request.draft'
    runs-on: ubuntu-latest
    steps:
      - run: echo 'test action'
